# fly.toml app configuration file generated for room241

app = 'room241'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'      # Désactive l'extinction automatique
  auto_start_machines = false     # Pas de démarrage à la demande via HTTP
  min_machines_running = 1        # Garde toujours au moins 1 machine active H24
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512                 # Augmenté à 512Mo pour stabiliser l'agent sans surcoût majeur
